/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.institute_management.attendance_new;

import com.institute_management.configurations.Config;
import com.institute_management.course_mgt.CourseDbConnection;
import com.institute_management.main.NewJFrame;
import com.institute_management.subject_mgt.DB.SubjectDbConnection;
import com.institute_management.util.CommonMethods;
import static com.institute_management.util.CommonMethods.validateMobileNo;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.Timer;

/**
 *
 * @author malindad
 */
public class express_initial_page extends javax.swing.JFrame {

    public CommonMethods cmMethds = new CommonMethods();
    Config config = new Config();
    dbConnection a = new dbConnection();
    public static SID_Bean bean_sid = new SID_Bean();
    String[] class_details = new String[3];
    String audioFilePath;
    int x = 0;
    boolean IS_First_attend = false;

    dbConnection conn = new dbConnection();

    SwingWorker sw = new SwingWorker() {
        @Override
        protected Object doInBackground() throws Exception {
            try {

                String audioFilePath = config.audioFilePath;
                AudioPlayerExample1 player = new AudioPlayerExample1();
                player.play(audioFilePath);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(new JFrame(), "Error In Alert System" + ex);
            }
            return null;
        }

        @Override
        public void done() {

        }
    };

    public express_initial_page(String st_id) {
        initComponents();
        cmMethds.setMonthMap();
        txtS_ID.grabFocus();
        txtS_ID.setText(st_id);
        jLabel3.setForeground(Color.white);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute_management/resources/gif/one.gif")));
        jPanel1.setBackground(new java.awt.Color(252, 253, 255));

    }

    public express_initial_page() {
        initComponents();
        txtS_ID.grabFocus();
        jLabel3.setForeground(Color.white);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute_management/resources/gif/one.gif")));
        jPanel1.setBackground(new java.awt.Color(252, 253, 255));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtS_ID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("ID");

        txtS_ID.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        txtS_ID.setForeground(new java.awt.Color(0, 153, 204));
        txtS_ID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 3, true));
        txtS_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtS_IDActionPerformed(evt);
            }
        });
        txtS_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtS_IDKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute_management/resources/gif/source.gif"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manual Mode Activated");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Mode");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute_management/resources/images/icons/430102-32.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addComponent(txtS_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtS_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtS_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtS_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtS_IDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jButton1MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try {
            this.dispose();
            NewJFrame a = new NewJFrame();
            a.setVisible(true);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void txtS_IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtS_IDKeyPressed
        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_ENTER) {
            //cmMethds.debugSlownessIssueLog(new Date()+ "-------------------");
            String s_id = txtS_ID.getText();
            //log
            //cmMethds.debugSlownessIssueLog(new Date()+ "****** S_ID : "+s_id );

            if (s_id.length() == config.card_number_length) {
                //log
                //cmMethds.debugSlownessIssueLog(new Date()+ "identified as card number" );

                try {
                    bean_sid.setS_id(a.get_sid_from_card_number(s_id));
                    IS_First_attend = a.IS_First_Entrence(bean_sid.getS_id());
                    //log
                    //cmMethds.debugSlownessIssueLog(new Date()+ "get sid by using card number : cardNo :"+ s_id);

                    class_details = a.get_relavant_Course(bean_sid.getS_id());
                    //log
                    //cmMethds.debugSlownessIssueLog(new Date()+ "Selected relavant class :"+class_details[0] );

                    if (class_details[0] != null) {
                        txtS_ID.setText("");
                        //mark attendence

                        int count = 0;
                        if (s_id.equals("")) {
                            JOptionPane.showMessageDialog(new JFrame(), "Please Select a Student first");
                        } else {
                            // TODO add your handling code here:
                            try {
                                boolean x = new CourseDbConnection().checkstudentinCourse(bean_sid.getS_id(), class_details[0]);
                                //log
                                //cmMethds.debugSlownessIssueLog(new Date()+ "check student existancy in the course");

                                //count = new SubjectDbConnection().markAttendence(class_details[0], bean_sid.getS_id(), new Date(), 1);
                                Calendar cal = Calendar.getInstance();
                                String curMonth = new SimpleDateFormat("MMMM").format(cal.getTime()).toLowerCase();
                                SelectedCourseStudentDetails detailBean = new SelectedCourseStudentDetails();

                                detailBean = a.get_lecturer_Course_details(class_details[0], bean_sid.getS_id(), detailBean);
                                //log
                                //cmMethds.debugSlownessIssueLog(new Date()+ "get_lecturer_Course_details");

                                if (x) {

                                    int weekNumber = a.get_weekNumber();
                                    //log
                                    //cmMethds.debugSlownessIssueLog(new Date()+ "get week number");

                                    //cmMethds.debugSlownessIssueLog(new Date()+ "start logic and mark attendance");
                                    if (weekNumber > 1) {
                                        count = new SubjectDbConnection().markAttendence(class_details[0], bean_sid.getS_id(), new Date(), 1);
                                        if (count == -1) {
                                            //JOptionPane.showMessageDialog(new JFrame(), "Student is already marked today attendence to this course");
                                            if (detailBean.getC_last_payment() != null) {
                                                if (detailBean.getC_last_payment().equals(curMonth)) {
                                                    audioFilePath = config.audioFilePath_already;
                                                    AudioPlayerExample1 player = new AudioPlayerExample1();
                                                    player.play(audioFilePath);
                                                } else {
                                                    audioFilePath = config.audioFilePath;
                                                    AudioPlayerExample1 player = new AudioPlayerExample1();
                                                    player.play(audioFilePath);
                                                }
                                            } else {
                                                audioFilePath = config.audioFilePath;
                                                AudioPlayerExample1 player = new AudioPlayerExample1();
                                                player.play(audioFilePath);
                                            }

                                        } else {
                                            //attendance success sound
                                            if (detailBean.getC_last_payment() != null) {
                                                if (detailBean.getC_last_payment().equals(curMonth)) {
                                                    audioFilePath = config.audioFilePath_success;
                                                    AudioPlayerExample1 player = new AudioPlayerExample1();
                                                    player.play(audioFilePath);
                                                } else {
                                                    audioFilePath = config.audioFilePath;
                                                    AudioPlayerExample1 player = new AudioPlayerExample1();
                                                    player.play(audioFilePath);
                                                }
                                            } else {
                                                audioFilePath = config.audioFilePath;
                                                AudioPlayerExample1 player = new AudioPlayerExample1();
                                                player.play(audioFilePath);
                                            }
                                            if (IS_First_attend) {
                                                //validate sms data
                                                SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy HH:mm");
                                                Date date = new Date();
                                                String mob1 = detailBean.getSms_contact1();
                                                String mob2 = detailBean.getSms_contact2();
                                                String f_mob = null;

                                                boolean xx = validateMobileNo(mob1);
                                                if (xx) {
                                                    f_mob = mob1;
                                                } else {
                                                    boolean xxx = validateMobileNo(mob2);
                                                    if (xxx) {
                                                        f_mob = mob2;
                                                    }
                                                }

                                                //insert  sms
                                                if (f_mob != null) {
                                                    String s_n = detailBean.getS_name().replace(" ", "+");
                                                    a.insert_arrive_SMS(detailBean.getS_gender(), s_n, formatter.format(date).replace(" ", "+"), f_mob, bean_sid.getS_id());
                                                }else{
                                                    
                                                }
                                            }
                                        }

                                    } else {
                                        count = new SubjectDbConnection().markAttendence(class_details[0], bean_sid.getS_id(), new Date(), 1);
                                        audioFilePath = config.audioFilePath_success;
                                        AudioPlayerExample1 player = new AudioPlayerExample1();
                                        player.play(audioFilePath);
                                        if (count == 1) {
                                            //validate sms data
                                            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                                            Date date = new Date();
                                            String mob1 = detailBean.getSms_contact1();
                                            String mob2 = detailBean.getSms_contact2();
                                            String f_mob = null;

                                            boolean xx = validateMobileNo(mob1);
                                            if (xx) {
                                                f_mob = mob1;
                                            } else {
                                                boolean xxx = validateMobileNo(mob2);
                                                if (xxx) {
                                                    f_mob = mob2;
                                                }
                                            }

                                            //insert  sms
                                            String s_n = detailBean.getS_name().replace(" ", "+");
                                            a.insert_arrive_SMS(detailBean.getS_gender(), s_n, formatter.format(date), f_mob, bean_sid.getS_id());

                                        }
                                    }

                                } else {
                                    //JOptionPane.showMessageDialog(new JFrame(), "Student have not enroll to this course");
                                    //error sound
                                    audioFilePath = config.audioFilePath_error;
                                    AudioPlayerExample1 player = new AudioPlayerExample1();
                                    player.play(audioFilePath);
                                }
                                // this.loadAttendLabel(attendList);
                            } catch (Exception ex) {
                                //JOptionPane.showMessageDialog(new JFrame(), "Error In Attendence Marking" + ex);
                                audioFilePath = config.audioFilePath_error;
                                AudioPlayerExample1 player = new AudioPlayerExample1();
                                player.play(audioFilePath);
                            }
                        }
                    } else {
                        //JOptionPane.showMessageDialog(new JFrame(), "No Match found");
                        txtS_ID.setText("");
                        audioFilePath = config.audioFilePath_error;
                        AudioPlayerExample1 player = new AudioPlayerExample1();
                        player.play(audioFilePath);
                    }

                } catch (Exception ex) {
                    Logger.getLogger(express_initial_page.class.getName()).log(Level.SEVERE, null, ex);
                }
                //cmMethds.debugSlownessIssueLog(new Date()+ "end logic and mark attendance");
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Please TAP the card.Can't use as manual");
                txtS_ID.setText("");
            }

        }
    }//GEN-LAST:event_txtS_IDKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(express_initial_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(express_initial_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(express_initial_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(express_initial_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new express_initial_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtS_ID;
    // End of variables declaration//GEN-END:variables
}
