/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.institute_management.attendence;

import com.institute_management.course_mgt.CourseDbConnection;
import com.institute_management.course_mgt.courseBean;
import com.institute_management.main.NewJFrame;
import com.institute_management.payment_mgt.NewPaymentDbConnection;
import com.institute_management.payment_mgt.paymentBean;
import com.institute_management.subject_mgt.DB.SubjectDbConnection;
import com.institute_management.user_mgt.UI.CreateUser;
import com.institute_management.util.ClockLabel;
import com.institute_management.util.CommonMethods;
import com.institute_management.util.autoSuggest;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;

/**
 *
 * @author mihiran_p
 */
public class attendenceCourse extends javax.swing.JFrame {

    /**
     * Creates new form attendenceCourse
     */
    SubjectDbConnection dbcon = new SubjectDbConnection();
    static String selectedCourseId;
    static ArrayList<String[]> subjectList = null;
    static ArrayList<String> subList = null;
    ArrayList<JLabel> jbuttonlableList = new ArrayList<>();
    Border border = BorderFactory.createLineBorder(Color.BLUE, 1);
    Border border1 = BorderFactory.createLineBorder(Color.GREEN, 2);
    Border border2 = BorderFactory.createLineBorder(Color.RED, 2);
    Border border3 = BorderFactory.createLineBorder(Color.RED, 1);
    static courseBean CourseBean;
    static BufferedImage img;
    NewPaymentDbConnection db = new NewPaymentDbConnection();
    Font f = new Font("ITALIC", Font.BOLD, 14);
    Font f1 = new Font("BOLD", Font.BOLD, 15);
    Font f3 = new Font("ARIAL", Font.PLAIN, 11);

    public attendenceCourse() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(1366, 768);
        initComponents();
        hideLables(jbuttonlableList);
        dateAttendence.setDate(new Date());
        this.loadCoursesOnDate(dateAttendence.getDate());
        jSID.setSelectedItem("");
        // test();
    }

    public void test() {
        final JTextField textfield = (JTextField) jSID.getEditor().getEditorComponent();
        // new autoSuggest().comboFilterOnCouresStudent(textfield.getText(), jSID, selectedCourseId);
        textfield.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent ke) {
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        new autoSuggest().comboFilterOnCouresStudent(textfield.getText(), jSID, selectedCourseId);
                    }
                });
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateAttendence = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jbtnLabel1 = new javax.swing.JLabel();
        jbtnLabel2 = new javax.swing.JLabel();
        jbtnLabel3 = new javax.swing.JLabel();
        jbtnLabel4 = new javax.swing.JLabel();
        jbtnLabel5 = new javax.swing.JLabel();
        jbtnLabel6 = new javax.swing.JLabel();
        jbtnLabel7 = new javax.swing.JLabel();
        jbtnLabel8 = new javax.swing.JLabel();
        jbtnLabel9 = new javax.swing.JLabel();
        jbtnLabel10 = new javax.swing.JLabel();
        jbtnLabel11 = new javax.swing.JLabel();
        jbtnLabel12 = new javax.swing.JLabel();
        jbtnLabel13 = new javax.swing.JLabel();
        jbtnLabel14 = new javax.swing.JLabel();
        jbtnLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblsname = new javax.swing.JLabel();
        lblsid = new javax.swing.JLabel();
        txtSName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSID = new javax.swing.JComboBox();
        ilbCName = new javax.swing.JPanel();
        lblcn = new javax.swing.JLabel();
        lblCM = new javax.swing.JLabel();
        lblcf = new javax.swing.JLabel();
        lblcg = new javax.swing.JLabel();
        lblCName = new javax.swing.JLabel();
        lblCMedium = new javax.swing.JLabel();
        lblCfee = new javax.swing.JLabel();
        lblCGrade = new javax.swing.JLabel();
        lblcl = new javax.swing.JLabel();
        lblCLec = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblA1 = new javax.swing.JLabel();
        lblA2 = new javax.swing.JLabel();
        lblA3 = new javax.swing.JLabel();
        lblA4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblA5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblP1 = new javax.swing.JLabel();
        lblP2 = new javax.swing.JLabel();
        lblP3 = new javax.swing.JLabel();
        lblP4 = new javax.swing.JLabel();
        lblP5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentHidden(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });

        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        dateAttendence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateAttendenceMouseClicked(evt);
            }
        });
        dateAttendence.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateAttendencePropertyChange(evt);
            }
        });

        jLabel4.setText("jLabel2");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        jLabel3.setText("jLabel1");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jLabel6.setText("jLabel2");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        jLabel5.setText("jLabel1");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });

        jLabel7.setText("jLabel2");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });

        jLabel8.setText("jLabel2");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        jLabel9.setText("jLabel2");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        jLabel10.setText("jLabel2");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        jLabel11.setText("jLabel2");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        jLabel12.setText("jLabel2");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        jLabel13.setText("jLabel2");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        jLabel14.setText("jLabel2");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        jLabel15.setText("jLabel2");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });

        jbtnLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel1.setText("   STOP");
        jbtnLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jbtnLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnLabel1MouseExited(evt);
            }
        });

        jbtnLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel2.setText("   STOP");
        jbtnLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel3.setText("   STOP");
        jbtnLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel4.setText("   STOP");
        jbtnLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel5.setText("   STOP");
        jbtnLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel6.setText("   STOP");
        jbtnLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel7.setText("   STOP");
        jbtnLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel8.setText("   STOP");
        jbtnLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel9.setText("   STOP");
        jbtnLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel10.setText("   STOP");
        jbtnLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel11.setText("   STOP");
        jbtnLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel12.setText("   STOP");
        jbtnLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel13.setText("   STOP");
        jbtnLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel14.setText("   STOP");
        jbtnLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jbtnLabel15.setText("   STOP");
        jbtnLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dateAttendence, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnLabel1, jbtnLabel2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dateAttendence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jbtnLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jbtnLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbtnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(622, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dateAttendence, jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        lblDate.setBackground(new java.awt.Color(0, 0, 0));
        lblDate.setText("jLabjel5");
        lblDate=new ClockLabel("date");

        lblDay.setBackground(new java.awt.Color(0, 0, 0));
        lblDay.setText("lblDay");
        lblDay=new ClockLabel("day");

        lblTime.setBackground(new java.awt.Color(0, 0, 0));
        lblTime.setText("lblTime");
        lblTime=new ClockLabel("time");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime)
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDay)
                    .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDate, lblDay, lblTime});

        lblsname.setText("Student Name");

        lblsid.setText("Student Id");

        jButton1.setText("Check In");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Payment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSID.setEditable(true);
        jSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSIDActionPerformed(evt);
            }
        });
        jSID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSIDPropertyChange(evt);
            }
        });

        ilbCName.setBorder(javax.swing.BorderFactory.createTitledBorder("Course Details"));

        lblcn.setText("Name        :");

        lblCM.setText("Medium    :");

        lblcf.setText("Fee            :");

        lblcg.setText("Grade       :");

        lblcl.setText("Lecturer  :");

        javax.swing.GroupLayout ilbCNameLayout = new javax.swing.GroupLayout(ilbCName);
        ilbCName.setLayout(ilbCNameLayout);
        ilbCNameLayout.setHorizontalGroup(
            ilbCNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ilbCNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ilbCNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ilbCNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblcf)
                        .addComponent(lblcg)
                        .addComponent(lblcn, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addComponent(lblCM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblcl))
                .addGap(18, 18, 18)
                .addGroup(ilbCNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCLec, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCfee, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ilbCNameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCM, lblcf, lblcg});

        ilbCNameLayout.setVerticalGroup(
            ilbCNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ilbCNameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ilbCNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblcn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ilbCNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCM)
                    .addComponent(lblCMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ilbCNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblcf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCfee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ilbCNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ilbCNameLayout.createSequentialGroup()
                        .addComponent(lblCGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCLec, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ilbCNameLayout.createSequentialGroup()
                        .addComponent(lblcg)
                        .addGap(18, 18, 18)
                        .addComponent(lblcl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Proceed");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ilbCName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsname, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblsid, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSName)
                            .addComponent(jSID, 0, 217, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsid))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsname)
                    .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4))
                .addGap(41, 41, 41))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ilbCName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Attendence"));
        jPanel7.setPreferredSize(new java.awt.Dimension(450, 600));

        jLabel16.setText("Date");

        jLabel17.setText("DAY");

        jLabel18.setText("TIME");

        jLabel19.setText("ATTENDENCE");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblA5)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel16)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel19))
                    .addComponent(lblA4)
                    .addComponent(lblA3)
                    .addComponent(lblA1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblA2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblA1, lblA2, lblA3, lblA4, lblA5});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(lblA1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblA2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblA3)
                .addGap(18, 18, 18)
                .addComponent(lblA4)
                .addGap(18, 18, 18)
                .addComponent(lblA5)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblA1, lblA2, lblA3, lblA4, lblA5});

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment"));
        jPanel8.setPreferredSize(new java.awt.Dimension(450, 600));

        jLabel20.setText("MONTH");

        jLabel21.setText("STATUS");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblP5, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblP4, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblP3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblP2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblP1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(81, 81, 81))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblP1, lblP2, lblP3, lblP4, lblP5});

        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblP1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblP2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblP3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblP4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblP5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblP1, lblP2, lblP3, lblP4, lblP5});

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentHidden

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        //jLabel3.setText("test");        // TODO add your handling code here:

        selectedCourseId = jLabel1.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }

    }//GEN-LAST:event_jLabel1MouseClicked

    private void dateAttendenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateAttendenceMouseClicked
        // TODO add your handling code here:
        if (subList != null) {
            subList.clear();
        }
        this.loadCoursesOnDate(dateAttendence.getDate());
    }//GEN-LAST:event_dateAttendenceMouseClicked

    private void dateAttendencePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateAttendencePropertyChange
        // TODO add your handling code here:
        if (subList != null) {
            subList.clear();
        }
        this.loadCoursesOnDate(dateAttendence.getDate());
    }//GEN-LAST:event_dateAttendencePropertyChange

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        if (subjectList.size() > 0) {
            jLabel1.setBorder(border);
            jLabel1.setFont(f);
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setBorder(null);
        jLabel1.setFont(f3);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1KeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        selectedCourseId = jLabel2.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        if (subjectList.size() > 1) {
            jLabel2.setBorder(border);
            jLabel2.setFont(f);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSIDActionPerformed
        // TODO add your handling code here:
        this.loadTextBoxStudentName();
    }//GEN-LAST:event_jSIDActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
//        // TODO add your handling code here:
//
//        try {
//            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-YYYY");
//            Date x = dateAttendence.getDate();
//            String day = sdf.format(x);
//
//            String[] dayArray = new String[4];
//            String[] date = day.split("\\-");
//            String sid = jSID.getSelectedItem().toString();
//            if (sid.equals("")) {
//                JOptionPane.showMessageDialog(new JFrame(), "Please Select a Student first");
//            } else {
//                //dbcon.insertIntoAttendence();
//                JOptionPane.showMessageDialog(new JFrame(), "Success");
//            }
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LinkedHashMap<String, String> paymentMap = null;
        try {
            if (jSID.getSelectedItem().toString().trim().equals("")) {
                JOptionPane.showMessageDialog(new JFrame(), "Please Select a Student first");
            } else {

                boolean studentExistancy = new CourseDbConnection().checkstudentExistancy(jSID.getSelectedItem().toString());
                if (studentExistancy) {
                    this.getImageById(jSID.getSelectedItem().toString());
                    ArrayList<AttendBean> attendList = null;
                    try {
                        attendList = dbcon.getattendencHistory(jSID.getSelectedItem().toString(), selectedCourseId);
                        paymentMap = db.getPaymentDetails(selectedCourseId, jSID.getSelectedItem().toString().trim(), 5);
                        this.loadAttendLabel(attendList);
                        this.loadPaymentlabel(paymentMap);
                        int stdID = Integer.parseInt(jSID.getSelectedItem().toString());

                        //load image
                        ImageIcon image = new ImageIcon("E:\\Image\\" + stdID + ".jpg");
                        Image im = image.getImage();
                        Image myImg = im.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                        Icon newImage = new ImageIcon(myImg);
                        lblImage.setIcon(newImage);
                    } catch (Exception e) {
                        throw e;
                    }
                } else {
                    String pathToImageSortBy = "/home/mihiran/Downloads/red-question-mark-clipart-9cRRzRdKi.png";
                    ImageIcon SortByIcon = new ImageIcon(getClass().getClassLoader().getResource(pathToImageSortBy));
                    //ImageIcon image = new ImageIcon("E:\\Image\\error.jpg");
                    Image im = SortByIcon.getImage();
                    Image myImg = im.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                    Icon newImage = new ImageIcon(myImg);
                    lblImage.setIcon(newImage);
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error In Attendence Marking" + e);

        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<AttendBean> attendList = null;

        if (jSID.getSelectedItem().toString().trim().equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Please Select a Student first");
        } else {
            // TODO add your handling code here:
            try {
                dbcon.markAttendence(selectedCourseId, jSID.getSelectedItem().toString().trim(), new Date(), 1);
                attendList = dbcon.getattendencHistory(jSID.getSelectedItem().toString(), selectedCourseId);
                this.loadAttendLabel(attendList);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(new JFrame(), "Error In Attendence Marking" + e);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // PaymentDashBoard 
        DateFormat dateFormat = new SimpleDateFormat("dd-MMMM-YYYY");
        DateFormat dateFormat2 = new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        DateFormat dateFormat1 = new SimpleDateFormat("EEEE");
        String dateattendence = dateFormat.format(new Date());
        String dateattendence1 = dateFormat1.format(new Date()).toLowerCase();
        System.out.println(dateattendence1);
        ArrayList<String> s1 = new ArrayList<>();

        String[] s = dateattendence.split("\\-");
        s1.add(s[1].toLowerCase());

        if (jSID.getSelectedItem().toString().trim().equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Please Select a Student first");
        } else {
            paymentBean paybean = new paymentBean();
            paybean.setAmount(CourseBean.getMonthlyFee());
            paybean.setCourseID(selectedCourseId);
            paybean.setDate(dateFormat2.format(new Date()).toString());
            paybean.setMonth(s1);
            paybean.setS_id(jSID.getSelectedItem().toString().trim());
            paybean.setYear(s[2]);
            //  paybean.se

            try {
                db.makePayment(paybean);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(new JFrame(), "Error In Payment Marking" + e);
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setBorder(null);
        jLabel2.setFont(f3);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setBorder(null);
        jLabel3.setFont(f3);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setBorder(null);
        jLabel4.setFont(f3);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setBorder(null);
        jLabel5.setFont(f3);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setBorder(null);
        jLabel6.setFont(f3);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setBorder(null);
        jLabel7.setFont(f3);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setBorder(null);
        jLabel8.setFont(f3);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        if (subjectList.size() > 2) {
            jLabel3.setBorder(border);
            jLabel3.setFont(f);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        if (subjectList.size() > 3) {
            jLabel4.setBorder(border);
            jLabel4.setFont(f);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        if (subjectList.size() > 4) {
            jLabel5.setBorder(border);
            jLabel5.setFont(f);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        if (subjectList.size() > 5) {
            jLabel6.setBorder(border);
            jLabel6.setFont(f);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        if (subjectList.size() > 6) {
            jLabel7.setBorder(border);
            jLabel7.setFont(f);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        if (subjectList.size() > 7) {
            jLabel8.setBorder(border);
            jLabel8.setFont(f);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        selectedCourseId = jLabel3.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        selectedCourseId = jLabel4.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        selectedCourseId = jLabel5.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        selectedCourseId = jLabel6.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        selectedCourseId = jLabel7.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        selectedCourseId = jLabel8.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        selectedCourseId = jLabel9.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        if (subjectList.size() > 8) {
            jLabel9.setBorder(border);
            jLabel9.setFont(f);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setBorder(null);
        jLabel9.setFont(f3);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        selectedCourseId = jLabel10.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        if (subjectList.size() > 9) {
            jLabel10.setBorder(border);
            jLabel10.setFont(f);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        jLabel10.setBorder(null);
        jLabel10.setFont(f3);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        selectedCourseId = jLabel11.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        if (subjectList.size() > 10) {
            jLabel11.setBorder(border);
            jLabel11.setFont(f);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        jLabel11.setBorder(null);
        jLabel11.setFont(f3);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        selectedCourseId = jLabel12.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        if (subjectList.size() > 11) {
            jLabel12.setBorder(border);
            jLabel12.setFont(f);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        jLabel12.setBorder(null);
        jLabel12.setFont(f3);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        selectedCourseId = jLabel13.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        if (subjectList.size() > 12) {
            jLabel13.setBorder(border);
            jLabel13.setFont(f);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        jLabel13.setBorder(null);
        jLabel13.setFont(f3);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        selectedCourseId = jLabel14.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        if (subjectList.size() > 13) {
            jLabel14.setBorder(border);
            jLabel14.setFont(f);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        jLabel14.setBorder(null);
        jLabel14.setFont(f3);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        selectedCourseId = jLabel15.getText();
        try {
            CourseBean = new CourseDbConnection().getCourseDetails(selectedCourseId);
            this.test();
            this.setCourseLable(CourseBean);

        } catch (Exception e) {
            System.out.println("Error" + e);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        if (subjectList.size() > 14) {
            jLabel15.setBorder(border);
            jLabel15.setFont(f);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        jLabel15.setBorder(null);
        jLabel15.setFont(f3);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseExited

    private void jbtnLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnLabel1MouseClicked
        // TODO add your handling code here:
        try {
            ArrayList<Integer> slist = this.getNotAttendentStudentForCourse(jLabel1.getText());
            String msg = "Please aware that your son/daughter not attend to" + jLabel1.getText() + "today -IPS";
            if (slist.size() > 0) {
                for (Integer slist1 : slist) {
                    dbcon.markAttendence(jLabel1.getText(), Integer.toString(slist1), dateAttendence.getDate(), 0);
                    String parentContactNo = dbcon.getParentContactNo(slist1);
                    if (this.validateNo(parentContactNo)) {
                        CommonMethods.sendsms(parentContactNo, msg);
                    }

                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error Occured --" + e);
        }

    }//GEN-LAST:event_jbtnLabel1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        NewJFrame mF;
        try {
            mF = new NewJFrame();
            mF.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(CreateUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbtnLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnLabel1MouseEntered
        if (subjectList.size() > 0) {
            jbtnLabel1.setBorder(border3);
        }

    }//GEN-LAST:event_jbtnLabel1MouseEntered

    private void jbtnLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnLabel1MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jbtnLabel1MouseExited

    private void jSIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSIDPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jSIDPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attendenceCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attendenceCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attendenceCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attendenceCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attendenceCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateAttendence;
    private javax.swing.JPanel ilbCName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JComboBox jSID;
    private javax.swing.JLabel jbtnLabel1;
    private javax.swing.JLabel jbtnLabel10;
    private javax.swing.JLabel jbtnLabel11;
    private javax.swing.JLabel jbtnLabel12;
    private javax.swing.JLabel jbtnLabel13;
    private javax.swing.JLabel jbtnLabel14;
    private javax.swing.JLabel jbtnLabel15;
    private javax.swing.JLabel jbtnLabel2;
    private javax.swing.JLabel jbtnLabel3;
    private javax.swing.JLabel jbtnLabel4;
    private javax.swing.JLabel jbtnLabel5;
    private javax.swing.JLabel jbtnLabel6;
    private javax.swing.JLabel jbtnLabel7;
    private javax.swing.JLabel jbtnLabel8;
    private javax.swing.JLabel jbtnLabel9;
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblA2;
    private javax.swing.JLabel lblA3;
    private javax.swing.JLabel lblA4;
    private javax.swing.JLabel lblA5;
    private javax.swing.JLabel lblCGrade;
    private javax.swing.JLabel lblCLec;
    private javax.swing.JLabel lblCM;
    private javax.swing.JLabel lblCMedium;
    private javax.swing.JLabel lblCName;
    private javax.swing.JLabel lblCfee;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblP2;
    private javax.swing.JLabel lblP3;
    private javax.swing.JLabel lblP4;
    private javax.swing.JLabel lblP5;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblcf;
    private javax.swing.JLabel lblcg;
    private javax.swing.JLabel lblcl;
    private javax.swing.JLabel lblcn;
    private javax.swing.JLabel lblsid;
    private javax.swing.JLabel lblsname;
    private javax.swing.JTextField txtSName;
    // End of variables declaration//GEN-END:variables

    private void loadCoursesOnDate(Date date) {

        try {
            ArrayList<JLabel> jlableList = new ArrayList<>();
            jlableList.add(jLabel1);
            jlableList.add(jLabel2);
            jlableList.add(jLabel3);
            jlableList.add(jLabel4);
            jlableList.add(jLabel5);
            jlableList.add(jLabel6);
            jlableList.add(jLabel7);
            jlableList.add(jLabel8);
            jlableList.add(jLabel9);
            jlableList.add(jLabel10);
            jlableList.add(jLabel11);
            jlableList.add(jLabel12);
            jlableList.add(jLabel13);
            jlableList.add(jLabel14);
            jlableList.add(jLabel15);

            jbuttonlableList.add(jbtnLabel1);
            jbuttonlableList.add(jbtnLabel2);
            jbuttonlableList.add(jbtnLabel3);
            jbuttonlableList.add(jbtnLabel4);
            jbuttonlableList.add(jbtnLabel5);
            jbuttonlableList.add(jbtnLabel6);
            jbuttonlableList.add(jbtnLabel7);
            jbuttonlableList.add(jbtnLabel8);
            jbuttonlableList.add(jbtnLabel9);
            jbuttonlableList.add(jbtnLabel10);
            jbuttonlableList.add(jbtnLabel11);
            jbuttonlableList.add(jbtnLabel12);
            jbuttonlableList.add(jbtnLabel13);
            jbuttonlableList.add(jbtnLabel14);
            jbuttonlableList.add(jbtnLabel15);

            int count = 0;
            SimpleDateFormat sdf = new SimpleDateFormat("EEEE");
            String day = sdf.format(date);
            subjectList = dbcon.getCourseDetailsOnDay(day);
            subList = CommonMethods.sortOnTime(subjectList);

            if (subList.size() > 0 || subList != null) {
                int noOfCourses = subList.size();
                for (int i = 0; i < noOfCourses; i++) {
                    count++;
                    jlableList.get(i).setText(subList.get(i));
                    //  jlableList.get(i).setText(subjectList.get(i)[0] + " Time :" + subjectList.get(i)[1]);
                    jlableList.get(i).setBackground(Color.darkGray);
                    jbuttonlableList.get(i).setVisible(true);
                }
                for (int i = count; i < 15; i++) {
                    count++;
                    jlableList.get(i).setText(null);
                    jbuttonlableList.get(i).setVisible(false);
                }
                //String[] jlableList=new String[noOfCourses];
            }
        } catch (Exception ex) {
            Logger.getLogger(attendenceCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
        // return subjectList;
    }

    private void setCourseLable(courseBean CourseBean) throws Exception {
        lblCGrade.setText(CourseBean.getGrade());
        lblCMedium.setText(CourseBean.getCourseMedium());
        lblCName.setText(CourseBean.getSubject());
        lblCfee.setText(Double.toString(CourseBean.getMonthlyFee()));
        lblCLec.setText(CourseBean.getLecturerName());
    }

    public void loadTextBoxStudentName() {
        try {

            String studentId = jSID.getSelectedItem().toString();
            if (studentId == null || studentId == "--" || studentId == "") {
                txtSName.setText(null);
            } else {

                String studentName = dbcon.getStudentNameOnId(studentId);

                txtSName.setText(studentName);

                //  JOptionPane.showMessageDialog(new JFrame(), "Success");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error in loading Student Name" + e);
        }
    }

    public void getImageById(String id) {
        /////////////////////////////////////////////////      
        Connection connection = null;
        String connectionURL = "jdbc:mysql://localhost:3306/institute_management";
        //////////////////////////////////////////////////        
        //  String query = "select S_IMAGE from student where S_ID = ?";
        // BufferedImage img = null;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            connection = DriverManager.getConnection(connectionURL, "root", "");
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select S_IMAGE from student where S_ID = " + 1);
            if (rs.next()) {
                byte[] img = rs.getBytes("S_IMAGE");

                //Resize The ImageIcon
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                lblImage.setIcon(newImage);
                lblImage.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "No Data");
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        // return img;
    }

//    public ImageIcon ResizeImage(String ImagePath, byte[] pic) throws IOException {
//        ImageIcon MyImage = null;
//        if (ImagePath != null) {
//            MyImage = new ImageIcon(ImagePath);
//        } else {
//            MyImage = new ImageIcon(pic);
//        }
//        Image img = MyImage.getImage();
//        lblImage.setIcon(MyImage);
//        //Image newImg = img.getScaledInstance(100, lblImage.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon image = new ImageIcon(img);
//
//        File outputfile = new File("saved.png");
//        ImageIO.write(bi, "png", outputfile);
//
//        lblImage.setIcon(image);
//        return image;
//
//    }
//    public void aaa() {
//
//        ResultSet rst = MyDB.rsFetch("SELECT `Picture` FROM `photo` WHERE `Employee ID` = '" + Data.User.getText() + "'");
//        while (rst.next()) {
//            Blob filenameBlob = rst.getBlob("Picture");
//            byte[] content = filenameBlob.getBytes(1L, (int) filenameBlob.length());
//            ImageIcon ik = new ImageIcon(content);
//            Image img = ik.getImage();
//            Image newimg = img.getScaledInstance(Data.picture.getWidth(), Data.picture.getHeight(), java.awt.Image.SCALE_SMOOTH);
//            ik = new ImageIcon(newimg);
//            Data.picture.setIcon(ik);
//        }
//    }
    private void loadAttendLabel(ArrayList<AttendBean> attendList) {
        ArrayList<JLabel> label = new ArrayList<>();
        label.add(lblA1);
        label.add(lblA2);
        label.add(lblA3);
        label.add(lblA4);
        label.add(lblA5);
        AttendBean a;
        String b;
        int i = 0;

        for (int j = 1; j <= attendList.size(); j++) {

            if (i <= 5) {
                a = attendList.get(i);
                if (a.getAttend() == 0) {
                    label.get(i).setBorder(border2);
                    b = "Not Attend";
                } else {
                    label.get(i).setBorder(border1);
                    b = "Attend";
                }
                label.get(i).setText(a.getDate() + "         " + a.getDay() + "                          " + a.getTime() + "                " + b);

                label.get(i).setFont(f);
                i++;
            } else {
                break;
            }

        }
    }

    private void loadPaymentlabel(LinkedHashMap<String, String> paymentMap) throws Exception {
        ArrayList<JLabel> label = new ArrayList<>();
        label.add(lblP1);
        label.add(lblA2);
        label.add(lblP3);
        label.add(lblP4);
        label.add(lblP5);

        int count = 0;
        for (Map.Entry<String, String> entry : paymentMap.entrySet()) {
            String value = entry.getValue().toString();
            String key = entry.getKey().toString();
            if (count == 0) {
                lblP1.setBorder(border1);
                if (value.contains("not")) {
                    lblP1.setBorder(border2);
                }
                lblP1.setText(key + "                             " + value);
                lblP1.setFont(f);
            }
            if (count == 1) {
                lblP2.setBorder(border1);
                if (value.contains("not")) {
                    lblP2.setBorder(border2);
                }
                lblP2.setText(key + "                             " + value);
                lblP2.setFont(f);
            }
            if (count == 2) {
                lblP3.setBorder(border1);
                if (value.contains("not")) {
                    lblP3.setBorder(border2);
                }
                lblP3.setText(key + "                             " + value);
                lblP3.setFont(f);
            }
            if (count == 3) {
                lblP4.setBorder(border1);
                if (value.contains("not")) {
                    lblP4.setBorder(border2);
                }
                lblP4.setText(key + "                             " + value);
                lblP4.setFont(f);
            }
            if (count == 4) {
                lblP5.setBorder(border1);
                if (value.contains("not")) {
                    lblP5.setBorder(border2);
                }
                lblP5.setText(key + "                              " + value);
                lblP5.setFont(f);
            }

            count++;
        }
    }

    public void hideLables(ArrayList<JLabel> jbuttonlableList) {
        for (JLabel jLabel : jbuttonlableList) {
            jLabel.setVisible(false);
        }
    }

    private ArrayList<Integer> getNotAttendentStudentForCourse(String text) throws Exception {
        ArrayList<Integer> slist;
        slist = dbcon.getNotAttendSList(text, dateAttendence.getDate());
        return slist;

    }

    private boolean validateNo(String parentContactNo) {
        boolean status = false;
        if (parentContactNo.matches("[0-9]+") && parentContactNo.length() == 10) {
            status = true;
        }
        return status;
    }

}
