/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.institute_management.user_mgt.UI;

import com.institute_management.main.NewJFrame;
import com.institute_management.user_mgt.DB.UserDbConnection;
import com.institute_management.user_mgt.bean.userBean;
import com.institute_management.util.CommonMethods;

import com.institute_management.util.Configurations;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Malinda Ranabahu
 */
public class NewLogin extends javax.swing.JFrame {

    UserDbConnection dbClass = new UserDbConnection();

    public NewLogin() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jLabel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel3KeyTyped(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 270, 40));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 40, 30));

        txtUserName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtUserName.setBorder(null);
        txtUserName.setOpaque(false);
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameKeyPressed(evt);
            }
        });
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 260, 30));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.setOpaque(false);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute_management/resources/images/IMS logins/finalLogin.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            int remainning = 0;
            boolean validUser = dbClass.validateUser(txtUserName.getText(), txtPassword.getText());

            remainning = dbClass.validateAttemts();

            if (validUser && remainning > 0) {
                userBean userbean = dbClass.getUserDetails(txtUserName.getText());
                Configurations.UserBean = userbean;

                if (CommonMethods.check_user_access(Configurations.Main_Page)) {
                    NewJFrame mf = new NewJFrame();
                    mf.setVisible(true);
                    this.dispose();
                    dbClass.UpdatevalidateAttemts(remainning);
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "This Page Not Configured Yet . . .");
                }

            } else if (remainning <= 0 && remainning > -2999) {
                JOptionPane.showMessageDialog(new JFrame(), "Please Renew The Package");
            } else if (remainning < -2999) {
                this.dispose();
                systemdown a = new systemdown();
                a.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Username or Password invalid");
                this.dispose();
                NewLogin login = new NewLogin();
                login.setVisible(true);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(new JFrame(), "Database connection fail");

        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                int remainning = 0;
                boolean validUser = dbClass.validateUser(txtUserName.getText(), txtPassword.getText());
                if (validUser) {
                    remainning = dbClass.validateAttemts();
                    if (remainning > 0) {
                        dbClass.UpdatevalidateAttemts(remainning);
                    }
                }
                if (validUser && remainning > 0) {
                    userBean userbean = dbClass.getUserDetails(txtUserName.getText());
                    Configurations.UserBean = userbean;

                    if (CommonMethods.check_user_access(Configurations.Main_Page)) {
                        NewJFrame mf = new NewJFrame();
                        mf.setVisible(true);
                        this.dispose();
                        //get connection 

                    } else {
                        JOptionPane.showMessageDialog(new JFrame(), "This Page Not Configured Yet . . .");
                    }

                } else if (remainning <= 0) {
                    JOptionPane.showMessageDialog(new JFrame(), "Please Renew The Package");
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "Username or Password invalid");
                    this.dispose();
                    NewLogin login = new NewLogin();
                    login.setVisible(true);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(new JFrame(), "Database connection fail");

            }
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                boolean validUser = dbClass.validateUser(txtUserName.getText(), txtPassword.getText());

                if (validUser) {
                    userBean userbean = dbClass.getUserDetails(txtUserName.getText());
                    Configurations.UserBean = userbean;

                    if (CommonMethods.check_user_access(Configurations.Main_Page)) {
                        NewJFrame mf = new NewJFrame();
                        mf.setVisible(true);
                        this.dispose();

                        // create dbconnection
                    } else {
                        JOptionPane.showMessageDialog(new JFrame(), "This Page Not Configured Yet . . .");
                    }

                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "Username or Password invalid");
                    this.dispose();
                    NewLogin login = new NewLogin();
                    login.setVisible(true);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(new JFrame(), "Database connection fail");

            }
        }
    }//GEN-LAST:event_txtUserNameKeyPressed

    private void jLabel3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
